Move assignments outside of if statement
PandoraPFA/PandoraSDK pull request #18
Opened 2024-11-25 15:33 UTC by tmadlener

Starting from version 13, gcc starts warning about this construct **only if it's negated** and when building with `-std=c++20`. No warning is raised with `-std=c++17` or when using gcc12 ([see mini demonstrator no compiler explorer with gcc12 and gcc13](https://godbolt.org/z/9Kv13199v)).

Explicitly lifting out the result of the assignment into a variable and checking that explicitly gets around this.

I will try to figure out whether the fact, that this works for `if ((a = b))`, but not for `if (!(a = b))` is a gcc bug or expected behavior.

This is, I think the better way to fix what I attempted in #17

2024-11-26 14:10 UTC, tmadlener commented
I have submitted [this thread](https://gcc.gnu.org/pipermail/gcc-help/2024-November/143869.html) to the *gcc-help* mailing list.

```cpp
if ((!(a = b)))
```
is the correct way of wrapping this in parentheses to silence the warning as explained in the thread. Also this is not a false positive, the main question at this point is why the warning is only emitted with c++20.

2024-12-11 09:06 UTC, AndyChappell requested changes
Hi Thomas, thanks for the proposed changes. I think my preference here would actually be a change of style. As these are PandoraInputTypes the = operator is overloaded here (see this [link](https://github.com/PandoraPFA/PandoraSDK/blob/6d5c96a96c1048d06010381dbf0ded5d2b0002b7/include/Pandora/PandoraInputTypes.h#L221), so the effective logic here is

```
m_chi2 = chi2;
if (m_chi2.IsInitialized())
   ...
```
   
In this case, I think this approach, here and in the other examples probably serves to both address the issue and add some clarity.

2024-12-13 07:36 UTC, tmadlener commented
Done.

2024-12-18 14:29 UTC, AndyChappell commented
@tmadlener The proposed changes look good. I will aim to integrate these into a release candidate early in the new year.

2025-01-06 11:58 UTC, merged

2025-01-06 13:06 UTC, AndyChappell commented
@tmadlener All of the changes (plus some additional admin) have now been merged across all three relevant repositories.

2025-01-06 14:51 UTC, tmadlener commented
Thanks a lot :)